apiVersion: v1
kind: Service
metadata:
  name: webook-mysql
spec:
  selector:
    app: webook-mysql
  ports:
    - port:  13309
      protocol: TCP
      targetPort: 3306
      nodePort: 30306
  type: NodePort
    